

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dd_db
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  backend:
    image: vineeth837/mean-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017/dd_db"
    depends_on:
      - mongo
    networks:
      - app-net
    ports:
      - "3000:3000" 

  frontend:
    image: vineeth837/mean-frontend:latest
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-net


  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
    driver: bridge
