version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongo_data:/data/db
    ports:
      # expose only if you need to inspect from host; otherwise remove this line
      - "27017:27017"
    networks: [app-net]

  backend:
    image: dockerhub_username/mean-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      PORT: "3000"
      MONGO_URI: "mongodb://mongo:27017/appdb"
      # add any other required env vars here
    depends_on:
      - mongo
    expose:
      - "3000"
    networks: [app-net]

  frontend:
    image: dockerhub_username/mean-frontend:latest
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"
    networks: [app-net]

  # Reverse proxy that binds to host:80 and routes to frontend and backend
  nginx:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks: [app-net]

volumes:
  mongo_data:

networks:
  app-net:
    driver: bridge
